### ISSUE TITLE
Adding accounts problems

### ISSUE THREAD

**Issue by BebeMischa** [cyberjunky/home-assistant-garmin_connect#1]
HA 2021.7.0 Supervised on Debian

HACS repository added.
Integration added.
Adding first account goes well, data is retrieved and posible to see in lovelace card.
But error is occuring and won't go away:

```
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.garmin_connect
Source: custom_components/garmin_connect/__init__.py:41
Integration: Garmin Connect (documentation)
First occurred: 16:50:21 (3 occurrences)
Last logged: 16:51:21

Connection error occurred during Garmin Connect login request: Connection error
```

Adding second account does not work.
After enter of credentials nothing happens.
Connection can not be made.

**Comment by BebeMischa** [comment]
Follow up...

the mentioned error disappeared after a while, multiple minutes.

Then adding a second account was possible.

That generated the same error for the second account.
Data were retrieved.

Also that error disappeared after some minutes.

So it looks, like everything works, it just get confused the first some minutes after adding an account, but sort it self out...

**Comment by cyberjunky** [comment]
I will have another look at this issue
