### ISSUE TITLE
Add state_class sensor property to support new long-term statistics feature

### ISSUE THREAD

**Issue by Valdorama** [cyberjunky/home-assistant-garmin_connect#10]
It would be nice to be able to use the Garmin Connect sensors in conjunction with the new 'long-term statistics' [feature](https://www.home-assistant.io/blog/2021/09/01/release-20219/#long-term-statistics-unlocked-for-all-sensors).

To do so requires that a new sensor property - [state_class ](https://developers.home-assistant.io/blog/2021/05/25/sensor_attributes/)- be implemented.

It would be cool to see something like step count or heart data available as a graph over a longer period of time.

**Comment by cyberjunky** [comment]
@Valdorama Thanks for the request, I added this feature to version 0.1.8, can you try it?

**Comment by Valdorama** [comment]
Thanks for adding this in, that's very appreciated. When I add a statistics graph card the list of available entities (that are long-term statistics-capable) includes the ones from the Garmin integration so it looks like it's working.
