### ISSUE TITLE
All automations lost after upgre 0.2.16 to 0.2.17

### ISSUE THREAD

**Issue by wallb35** [cyberjunky/home-assistant-garmin_connect#100]
Every time I upgraded to latest Garmin connect plugin 0.2.17 in home assistant 0.9.x I lose all my automations.
Unable to recreate them.
Have to restore a backup.

**Comment by cyberjunky** [comment]
@wallb35 oh really? Anything in the logs when installing/restarting ha and/or when you try to recreate them? Can you provide me one of them so I can test locally?

**Comment by wallb35** [comment]
I just found the issue. It was on my side. some sensors saw there name changing causing errors in automations. I solve the issue sorry for the bad identification.

**Comment by cyberjunky** [comment]
@wallb35 no problem, thank you for the update!
