### ISSUE TITLE
Tracking equipment data

### ISSUE THREAD

**Issue by Crimby88** [cyberjunky/home-assistant-garmin_connect#101]
It would be great to track equipment / gear data (current vs max distance)

**Comment by cyberjunky** [comment]
@Crimby88 the inderlaying library is able to do this (at least get gear data) I'm planning to rewrite stuff and add features to get it into the official Home Assistant code, wish me luck ;)

**Comment by Crimby88** [comment]
> @Crimby88 the inderlaying library is able to do this (at least get gear data) I'm planning to rewrite stuff and add features to get it into the official Home Assistant code, wish me luck ;)

Thank you! And I wish you good luck! Much appreciated

**Comment by cyberjunky** [comment]
Gear data is included for some time, closing
