### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by k4nfr3** [cyberjunky/home-assistant-garmin_connect#104]
Since a few days, it's no longer able to connect.
Running version 2023.9.2
Even after upgrading to 2023.9.3, same issue.

I've deleted config and restarted but same issue still.
Any help would be appreciated
Regards

=====================================

This error originated from a custom integration.

Logger: custom_components.garmin_connect.config_flow
Source: custom_components/garmin_connect/config_flow.py:47
Integration: Garmin Connect (documentation, issues)
First occurred: 5:34:49 PM (1 occurrences)
Last logged: 5:34:49 PM

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/garmin_connect/config_flow.py", line 47, in async_step_user
    await self.hass.async_add_executor_job(api.login)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/garminconnect/__init__.py", line 270, in login
    return self.authenticate()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/garminconnect/__init__.py", line 403, in authenticate
    self.display_name = user_prefs["displayName"]
                        ~~~~~~~~~~^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by cyberjunky** [comment]
Did it work before on version 0.2.17? I saw some people reporting similar issues on my python package pagehttps://github.com/cyberjunky/python-garminconnect, could it be a Garmin service down issue? People on Reddit reported some issues with app as well..

**Comment by k4nfr3** [comment]
Hi,
I'm fairly new and didn't have you old version installed.
I do not know about Garmin service down, let's wait a couple of days and I will see if it comes backup.
Regards

**Comment by cyberjunky** [comment]
I had the issue myself on a system, and after the update of HA I restarted, and it came back to life, not sure wat caused it, so could  happen again..
