### ISSUE TITLE
security code for garmin account 

### ISSUE THREAD

**Issue by susertux** [cyberjunky/home-assistant-garmin_connect#106]
my garmin account needs to be protected with security code

add on will actually not work, please add poosibility or use protected accounts

**Comment by prsmith777** [comment]
Same here.  I need to have 2FA on my account and there is no option to enter a code to proceed.

Please update

**Comment by cyberjunky** [comment]
Will try to add support for it..

**Comment by Tokke77** [comment]
Same for me, since activation of 2FA I cant connect anymore.

**Comment by cyberjunky** [comment]
Closed because added to parent ticket https://github.com/cyberjunky/home-assistant-garmin_connect/issues/117

**Comment by Gawronnek** [comment]
I use the Mi Scale Exporter application on Android, the author Łukasz Świderski also had a problem with 2FA, but he managed to solve it, a window appears where we enter the received code, maybe he could tell us how to solve it in your application, he is a very kind man
