### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by sunjunyan** [cyberjunky/home-assistant-garmin_connect#108]
when I input username and password,  login,  shown :Unexpected error. 
pls help me,  the username and pw is correct.

**Comment by rjbrown99** [comment]
+1 same issue, seems that Garmin now requires an email-based code in addition to username and password.

**Comment by craigrouse** [comment]
In the readme, it states that 2 factor authentication isn't yet supported, so if you've enabled it, you won't be able to use this integration. Unfortunately, there's no way to revert once you've enabled 2 factor authentication. The integration works fine if you haven't enabled 2fa.

**Comment by rjbrown99** [comment]
Thanks, perhaps we can change the subject of this into a feature request for 2 factor auth for those of us that enabled it? It does send the 2 factor email upon registration in HA so the code is delivered.

**Comment by cyberjunky** [comment]
Will try to add this feature, needs a bit of a rewrite though

**Comment by cyberjunky** [comment]
https://github.com/cyberjunky/home-assistant-garmin_connect/issues/117

**Comment by cyberjunky** [comment]
Closed because added to parent ticket https://github.com/cyberjunky/home-assistant-garmin_connect/issues/117
