### ISSUE TITLE
garmin jr

### ISSUE THREAD

**Issue by zymex22** [cyberjunky/home-assistant-garmin_connect#11]
is it possible to connect to a garmin connect jr. watch? accounts for those are under an adults account and dont have a seperate login for them and i dont see them on list of active sensors under my account

**Comment by cyberjunky** [comment]
I'm afraid not, mind you the Garmin API is closed, so all needs to be done by reverse engineering.

**Comment by Jogge** [comment]
@zymex22 I am in the same situation. Have you tried making a GDPR request using your Right to Data Portability?

https://ico.org.uk/for-organisations/guide-to-data-protection/guide-to-the-general-data-protection-regulation-gdpr/individual-rights/right-to-data-portability/
