### ISSUE TITLE
Any plans for a new release? 

### ISSUE THREAD

**Issue by ray0711** [cyberjunky/home-assistant-garmin_connect#112]
Hi,
python-garminconnect has quite some fixes and additions since the last dependency bump.
It would be great to see a new release.

Thanks for the great component!

**Comment by cyberjunky** [comment]
Yes a lot of plans, but not so much time, will try to squeeze it in though, the new python-garminconnect library makes the way for 
a lot of new feature to the HA integration, bit that needs a bit of a rewrite.

**Comment by Cas7or** [comment]
Can't wait! Love your work, very much looking forward to new version!

**Comment by cyberjunky** [comment]
I switched to the new package version! Also have some time to work on issues/features.
