### ISSUE TITLE
Errors after HA 2024.1 update

### ISSUE THREAD

**Issue by Traxeronus** [cyberjunky/home-assistant-garmin_connect#115]
Logger: custom_components.garmin_connect
Source: custom_components/garmin_connect/__init__.py:75

Error occurred during Garmin Connect login request: Too many requests

Logger: homeassistant.const
Source: helpers/deprecation.py:204

LENGTH_METERS was used from garmin_connect, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.METERS instead, please create a bug report at https://github.com/cyberjunky/home-assistant-garmin_connect/issues
MASS_KILOGRAMS was used from garmin_connect, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfMass.KILOGRAMS instead, please create a bug report at https://github.com/cyberjunky/home-assistant-garmin_connect/issues
TIME_MINUTES was used from garmin_connect, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTime.MINUTES instead, please create a bug report at https://github.com/cyberjunky/home-assistant-garmin_connect/issues
TIME_YEARS was used from garmin_connect, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTime.YEARS instead, please create a bug report at https://github.com/cyberjunky/home-assistant-garmin_connect/issues

**Comment by cyberjunky** [comment]
I fixed them in 0.2.19! Thanks for reporting!
