### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by nicklasloje** [cyberjunky/home-assistant-garmin_connect#12]
Hi
  It asks for username and code.

But my login is via email
and it does not work ...

and I have tried that but just say wrong username or code

What is I doing wrong?

Logged in to the Garmin connect website without any problems

**Comment by kimvonmullen** [comment]
> Hi It asks for username and code.
> 
> But my login is via email and it does not work ...
> 
> and I have tried that but just say wrong username or code
> 
> What is I doing wrong?
> 
> Logged in to the Garmin connect website without any problems

Hi,
I have the same problem and can also log into garmin web page.

**Comment by The2rB** [comment]
First time user. Tried to log in. Same problem as described. 
Have TFA active, if relevant. Haven't tried to disable it.

**Comment by StefanoA70** [comment]
Same for me,
I tried several times using both "Name" or "email" + password but always got login/connection error
TFA not active on my account...

hope somebody can help with this issue

**Comment by cyberjunky** [comment]
Release 0.1.4 should work better.
