### ISSUE TITLE
Is it possible to get a sensor for when your Garmin Watch tells you to move?

### ISSUE THREAD

**Issue by ncd7** [cyberjunky/home-assistant-garmin_connect#138]
I'd love to create an automation that flashes the lights and gives an audio prompt on my smart speakers when my Garmin Forerunner reminds me to move. Is this possible? Thank you.

**Comment by LazyTarget** [comment]
That is probably something that is calculated and triggered on the actual watch. 

I would be very surprised if that something that there is an _public_ API or event for
