### ISSUE TITLE
Garmin Live Track status in home assistant

### ISSUE THREAD

**Issue by andrebbruno** [cyberjunky/home-assistant-garmin_connect#14]
Is there any chance to enable Live Track status in HA? I can think of a few automations to when you start an activity, it would be awesome.

**Comment by cyberjunky** [comment]
Not possible, sorry.

**Comment by amokrunner** [comment]
> Is there any chance to enable Live Track status in HA? I can think of a few automations to when you start an activity, it would be awesome.

I am thinking there may be a "messy" way to achieve this by using the imap integration and the email sent by garmin connect when live track begins, which gives you what you need to get the livetrack status for that session via json

**Comment by fatuuse** [comment]
One "messy" solution! 🙂

**Comment by fatuuse** [comment]
> Is the livetrack link visible somewhere on the Garmin Connect site when it's active?

I haven't found it (yet) unfortunately... I think the function is "stand alone" from Connect login part.
