### ISSUE TITLE
Garmin Connect 

### ISSUE THREAD

**Issue by stinkyfromusc** [cyberjunky/home-assistant-garmin_connect#15]
I noticed yesterday that the information I'm getting from Garmin is sparse to absent. 

Presently, I am getting only the following

Active KiloCalories
Burned KiloCalories
Next Alarm Time
Sedentary Time
Total Distance Mtr
Total KiloCalories

I also get the following error when I reboot:
> This error originated from a custom integration.
> 
> Logger: custom_components.garmin_connect
> Source: custom_components/garmin_connect/__init__.py:78
> Integration: Garmin Connect (documentation, issues)
> First occurred: 4:24:56 PM (4 occurrences)
> Last logged: 4:25:45 PM
> 
> Connection error occurred during Garmin Connect login request: Connection error

**Comment by cyberjunky** [comment]
Did you look at all the (by default) disabled entities? What kind of Garmin Devices do you sync?

**Comment by stinkyfromusc** [comment]
These were working until recently.  I’m using a Vivoactive 4 and an Edge 520.

**Comment by cyberjunky** [comment]
@stinkyfromusc Did you try the latest home-assistant Garmin Connect version? There was a fix for the connect issue, it now sometimes failes after a restart but it retries automatically.
