### ISSUE TITLE
Garmin Connect TFA not supported 

### ISSUE THREAD

**Issue by The2rB** [cyberjunky/home-assistant-garmin_connect#16]
Trying to log in while TFA activated returns "Invalid authentication".
This makes it impossible to log in.

**Comment by cyberjunky** [comment]
2FA is not supported, no technical info on how to build it yet

**Comment by Willow-Systems** [comment]
Might be worth putting this in the readme. I setup a new integration, forgot about it, and next time I checked my email it was filled with 2FA codes from Garmin!

**Comment by pentafive** [comment]
Just wanted to share that this other project now has Garmin Connect 2FA. Perhaps this could reuse some of that work? https://github.com/philosowaffle/peloton-to-garmin/discussions/408
