### ISSUE TITLE
2FA not supported..

### ISSUE THREAD

**Issue by Rolfgithub2** [cyberjunky/home-assistant-garmin_connect#165]
I can't connect to my account for it is protected by 2FA.

The setup of the integration fails with an error: "unexpected error"
At the same time I  receive the second factor on my telephone.. 
Can this be added...

Thanks!!

**Comment by velaar** [comment]
Please search before opening a new issue. See: https://github.com/cyberjunky/home-assistant-garmin_connect/issues/117

**Comment by Rolfgithub2** [comment]
Hi Velaar, sorry just missed it. I will close This one
