### ISSUE TITLE
HACS install: Repository 'cyberjunky/home-assistant-garmin_connect' exists in the store.

### ISSUE THREAD

**Issue by shermozle** [cyberjunky/home-assistant-garmin_connect#17]
I get this message when I try to add the custom repository:
![image](https://user-images.githubusercontent.com/1082196/142551560-323ddcbd-2cab-4bd3-b1d5-d941985fb85e.png)

Yet I also can't add it from the list, which is super confusing:
![image](https://user-images.githubusercontent.com/1082196/142551630-ad30bc19-3189-4d98-87f6-54d0dc6881c9.png)

What's going on here?

**Comment by millerjp1986** [comment]
Im getting this same thing.  I will also add, I tried manually installing via copying the 'garmin_connect' to the 'custom_components' directory, but then after a reboot its still not finding the integration in 'Home Assistant > Coinfiguration > Integrations > +Add Integration'

**Comment by eric-silva89** [comment]
ditto @millerjp1986

**Comment by cyberjunky** [comment]
I just tested it, and cannot reproduce.
![image](https://user-images.githubusercontent.com/5447161/143409514-13ed150a-0cbc-4501-8e71-b529c0a7a959.png)

Without adding the repo to HACS (which is not needed since it's already in there) I can still install it without problems.
Did multiple remove integration and reboots.

So I need more information. Which HA version to start with

**Comment by shermozle** [comment]
Wow okay. Well I'm on core-2021.11.4 though it's prompting me to go to .5 which I'll do in a second and try again.
Just upgraded and have the same problem.

**Comment by cyberjunky** [comment]
Do you have custom repo for garmin in HACS added or stil sitting there?

**Comment by shermozle** [comment]
No the only custom repo is for a camera I have.

**Comment by eric-silva89** [comment]
I'm on core-2021.11.5 and the only other custom integration happens to be the cyberjunky/home-assistant-google_fit

**Comment by obbers** [comment]
Does it matter that the country in hacs.json is set to NL?

**Comment by cyberjunky** [comment]
> I just forked this and removed the country listing from the hacs.json. It's available now.

You removed the entry completely?
Can you share, I will commit it.

**Comment by cyberjunky** [comment]
Country fix implemented in 0.1.5
