### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by usefrancisco3210** [cyberjunky/home-assistant-garmin_connect#19]
I tried to log in to my garmin account, but it always says 'Failed to connect'.I don't know if I'm missing something, but it just won't log into my account.

**Comment by BinnFudde** [comment]
This issue seems to be a duplicate of #8. Sometimes the initial connect is failed, but give it some time or restarts.

**Comment by cyberjunky** [comment]
Release 0.1.4 should work better.
