### ISSUE TITLE
failed to connect

### ISSUE THREAD

**Issue by molnarti** [cyberjunky/home-assistant-garmin_connect#2]
I have installed the integration over HACS, added it over the Integrations menu, but when entering the logins i get a failed to connect message. It's not a bad password issue, because entering random email and password gets me a different error message. I see nothing in the logs relevant to garmin connect.

Using Home Assistant container 2021.7.1

**Comment by yuckypants** [comment]
I'm experiencing the same issue.

**Comment by Melantrix** [comment]
Same issue for me on version 2021.8.1.

**Comment by gitthangbaby** [comment]
Home Assistant 2021.8.5 - i can't even see it in integrations/devices/entities.
just one runtime mention in logs: "We found a custom integration garmin_connect which has not been tested by Home Assistant" otherwise no evidence of it.

**Comment by arallsopp** [comment]
Same issue here. If I put junk in it says "Invalid authentication" but putting in my correct details returns "Failed to connect"

**Comment by arallsopp** [comment]
Been using it via hacs, after seeing it removed. It did connect eventually, also. :)
