### ISSUE TITLE
Mismatch of versions 0.2.22?

### ISSUE THREAD

**Issue by cskiwi** [cyberjunky/home-assistant-garmin_connect#202]
I just updated and got the following error:

> Setup failed for custom integration 'garmin_connect': Requirements for garmin_connect not found: ['garminconnect>=0.2.22'].

My version is 0.2.20

**Comment by cyberjunky** [comment]
garminconnect 0.2.22 is available on pypi since this morning, I no idea why you cannot retrieve it from there

https://pypi.org/project/garminconnect/

Can you restart HA once more?

![image](https://github.com/user-attachments/assets/3cab97ff-4360-4819-8697-28b94cba101c)

**Comment by cyberjunky** [comment]
And the strange thing is also that the garminconnect package is in use by a ton of other projects, and people confirmed they upgraded to 0.2.22 and had working project again, i have no clue why some HA instances has this issue

**Comment by GreJ0** [comment]
Also a problem here with 0.2.20 only 0.2.21 available on HACS

**Comment by cyberjunky** [comment]
Ah, just before the messages you post, I see this one ```Unable to install package garminconnect>=0.2.22: error: Failed to prepare distributions Caused by: Failed to download and build `withings-sync==4.2.6` Caused by: Build backend failed to determine requirements with `build_wheel()` (exit status: 1) [stderr] Traceback (most recent call last): File "<string>", line 14, in <module> File "/tmp/.tmp7Z60mn/builds-v0/.tmpdRcDkn/lib/python3.12/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel return self._get_build_requires(config_settings, requirements=[]) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/.tmp7Z60mn/builds-v0/.tmpdRcDkn/lib/python3.12/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires self.run_setup() File "/tmp/.tmp7Z60mn/builds-v0/.tmpdRcDkn/lib/python3.12/site-packages/setuptools/build_meta.py", line 522, in run_setup``` there seem to be an issue with withings-sync==4.2.6, maybe a conflict with HA or parts of it, will investigate

**Comment by cyberjunky** [comment]
![image](https://github.com/user-attachments/assets/21ba91ae-b8f7-469a-9f1c-ff49fc53e143)

A new version just uploaded 3 hours ago doesn't seem to work

**Comment by cyberjunky** [comment]
Guys, can you try new version of my custom component? It should be fixed!

**Comment by Dorian5-coder** [comment]
Hello @cskiwi  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by johnnieblows** [comment]
Also had the issues described above, installed 0.2.22 and restarted - working correctly.

Thank you!

**Comment by cooper645** [comment]
@cyberjunky All sorted. Thanks for the swift response

**Comment by cskiwi** [comment]
Indeed updating fixed the issue
