### ISSUE TITLE
bodyMass doesn't exist for Garmin Index Smart Scale

### ISSUE THREAD

**Issue by niculescurobert** [cyberjunky/home-assistant-garmin_connect#21]
https://github.com/cyberjunky/home-assistant-garmin_connect/blob/78f5266a5f8c18ac997c93e3eb66b502adae4213/custom_components/garmin_connect/const.py#L351

Please make this changes:
bodyMass with boneMass
mdi:food with mdi:bone

"boneMass": ["Bone Mass", MASS_KILOGRAMS, "mdi:bone", None, False],

this is the correct "measured value name" for Garmin Index Smart Scale or Index S2 Smart Scale. (https://www.garmin.com/nl-NL/p/679362/pn/010-02294-13#overview)

![Garmin Index Smart Scale](https://user-images.githubusercontent.com/92642632/147292772-e5c848af-410e-4491-af4a-f59a4b7e97b1.jpg)

**Comment by niculescurobert** [comment]
![GISC](https://user-images.githubusercontent.com/92642632/147291635-5acdc842-8cd8-4cdb-9f07-c59372138251.jpg)

**Comment by cyberjunky** [comment]
Fixed in release 0.1.4, thanks!
