### ISSUE TITLE
Unknown error occurred during Garmin Connect login request

### ISSUE THREAD

**Issue by Tazmanian79** [cyberjunky/home-assistant-garmin_connect#212]
Since update to HA 2024.12.2 I have this error

`Logger: custom_components.garmin_connect
Bron: custom_components/garmin_connect/__init__.py:82
integratie: Garmin Connect ([documentatie](https://github.com/cyberjunky/home-assistant-garmin_connect), [problemen](https://github.com/cyberjunky/home-assistant-garmin_connect/issues))
Eerst voorgekomen: 12:06:16 (1 gebeurtenissen)
Laatst gelogd: 12:06:16

Unknown error occurred during Garmin Connect login request
Traceback (most recent call last):
  File "/config/custom_components/garmin_connect/__init__.py", line 82, in async_login
    await self.hass.async_add_executor_job(self._api.login)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/garminconnect/__init__.py", line 239, in login
    self.display_name = self.garth.profile["displayName"]
                        ^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'profile'`

**Comment by schumissimo63** [comment]
Same issue here

**Comment by canedje** [comment]
here also

**Comment by eleutscher** [comment]
Yep, same

Unknown error occurred during Garmin Connect login request
Traceback (most recent call last):
  File "/config/custom_components/garmin_connect/__init__.py", line 82, in async_login
    await self.hass.async_add_executor_job(self._api.login)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/garminconnect/__init__.py", line 239, in login
    self.display_name = self.garth.profile["displayName"]
                        ^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'profile'

**Comment by baltsi** [comment]
Same here


Traceback (most recent call last):
  File "/config/custom_components/garmin_connect/__init__.py", line 82, in async_login
    await self.hass.async_add_executor_job(self._api.login)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/garminconnect/__init__.py", line 239, in login
    self.display_name = self.garth.profile["displayName"]
                        ^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'profile

**Comment by baltsi** [comment]
Maybe the python upgrade to home assistant core?

**Comment by kozerscy** [comment]
I was working for me on 2024.12.1 and stopped with 2024.12.2

**Comment by cyberjunky** [comment]
> Maybe the python upgrade to home assistant core?

From which to which version we went?

**Comment by ivercellino** [comment]
Same issue here.

**Comment by sandhase92** [comment]
Same issue here.

**Comment by perabo65** [comment]
> > Maybe the python upgrade to home assistant core?
> 
> From which to which version we went?

From 3.12 to 3.13

**Comment by crusader85** [comment]
Same here on 2024.12.2

**Comment by cyberjunky** [comment]
Can you check 0.2.23 release, some people reported a specific version of the underlaying library worked so I pinned this version to that.

**Comment by perabo65** [comment]
Tried directly and it's working on a HA docker installation. Wow, great, thanks a lot!

**Comment by Tazmanian79** [comment]
Working again :-)

**Comment by alistair-marshall** [comment]
Thanks! Once I worked out how to force a re download it is working.

**Comment by Tazmanian79** [comment]
go to HACS - garmin connect - update information

and you will get message to update the integration in settings menu

**Comment by sinanqasha** [comment]
Is it working for people with 2fa enabled?

**Comment by cyberjunky** [comment]
@sinanqasha no it never did, but there is a new version of underlaying lib which has that functionality, I will try to create a new version soon.

**Comment by olines** [comment]
Same issue on 2024.12.4 (docker)
It will connect ok on release 0.2.20 but nothing newer...

**Comment by cyberjunky** [comment]
@olines can you try version 0.2.25, although nothing is this area changed, maybe you can post the errors again.

**Comment by verhoevendanny** [comment]
Since version 0.2.23 the same issue 
[home-assistant_garmin_connect_2024-12-20T10-12-57.356Z.log](https://github.com/user-attachments/files/18209256/home-assistant_garmin_connect_2024-12-20T10-12-57.356Z.log)

**Comment by cyberjunky** [comment]
> Since version 0.2.23 the same issue [home-assistant_garmin_connect_2024-12-20T10-12-57.356Z.log](https://github.com/user-attachments/files/18209256/home-assistant_garmin_connect_2024-12-20T10-12-57.356Z.log)

We it's actually a little bit different issue, I will try to fix...

**Comment by cyberjunky** [comment]
Version 0.2.26 is available with the fix

**Comment by verhoevendanny** [comment]
Still not working, but another Error

Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.garmin_connect
Bron: custom_components/garmin_connect/__init__.py:82
integratie: Garmin Connect (documentatie, problemen)
Eerst voorgekomen: 12:25:18 (2 gebeurtenissen)
Laatst gelogd: 12:25:57

Unknown error occurred during Garmin Connect login request
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/garth/http.py", line 143, in request
    self.last_resp.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://sso.garmin.com/sso/signin?id=gauth-widget&embedWidget=true&gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed&service=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed&source=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed&redirectAfterAccountLoginUrl=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed&redirectAfterAccountCreationUrl=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/garmin_connect/__init__.py", line 82, in async_login
    await self.hass.async_add_executor_job(self._api.login)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/garminconnect/__init__.py", line 235, in login
    self.garth.login(
    ~~~~~~~~~~~~~~~~^
        self.username, self.password, prompt_mfa=self.prompt_mfa
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/garth/http.py", line 164, in login
    self.oauth1_token, self.oauth2_token = sso.login(
                                           ~~~~~~~~~^
        *args, **kwargs, client=self
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/garth/sso.py", line 127, in login
    client.post(
    ~~~~~~~~~~~^
        "sso",
        ^^^^^^
    ...<8 lines>...
        ),
        ^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/garth/http.py", line 155, in post
    return self.request("POST", *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/garth/http.py", line 145, in request
    raise GarthHTTPError(
    ...<2 lines>...
    )
garth.exc.GarthHTTPError: Error in request: 429 Client Error: Too Many Requests for url: https://sso.garmin.com/sso/signin?id=gauth-widget&embedWidget=true&gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed&service=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed&source=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed&redirectAfterAccountLoginUrl=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed&redirectAfterAccountCreationUrl=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fembed

**Comment by cyberjunky** [comment]
@verhoevendanny due to all the tries and failures garmin blocked your account, I think for 30-60 minutes.
Can you try in a while and let me know? 
In a future version I will try to catch this error a bit better, so at least it doesn't fill the log.

**Comment by verhoevendanny** [comment]
> @verhoevendanny due to all the tries and failures garmin blocked your account, I think for 30-60 minutes. Can you try in a while and let me know? In a future version I will try to catch this error a bit better, so at least it doesn't fill the log.

Indeed it is solved in the mean time! Thx Ron

**Comment by olines** [comment]
> @olines can you try version 0.2.25, although nothing is this area changed, maybe you can post the errors again.

0.2.25 throws this error:

`Unexpected error fetching garmin_connect data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/garmin_connect/__init__.py", line 194, in _async_update_data
    if "hrvSummary" in hrv_data:
       ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable`

**Comment by olines** [comment]
> > @olines can you try version 0.2.25, although nothing is this area changed, maybe you can post the errors again.
> 
> 0.2.25 throws this error:
> 
> `Unexpected error fetching garmin_connect data Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh self.data = await self._async_update_data() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/garmin_connect/__init__.py", line 194, in _async_update_data if "hrvSummary" in hrv_data: ^^^^^^^^^^^^^^^^^^^^^^^^ TypeError: argument of type 'NoneType' is not iterable`

But... 0.2.26 is now working on 2024.12.5 🙌 Thank you!
