### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by iamspido** [cyberjunky/home-assistant-garmin_connect#215]
Get following error since 0.2.24:

```
hass  | 2024-12-19 22:56:36.256 ERROR (MainThread) [custom_components.garmin_connect] Unexpected error fetching garmin_connect data
hass  | Traceback (most recent call last):
hass  |   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh
hass  |     self.data = await self._async_update_data()
hass  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
hass  |   File "/config/custom_components/garmin_connect/__init__.py", line 195, in _async_update_data
hass  |     hrvStatus = hrv_data["hrvSummary"]
hass  |                 ~~~~~~~~^^^^^^^^^^^^^^
hass  | TypeError: 'NoneType' object is not subscriptable
```

Running on Home Assistant 2024.11.3

**Comment by cyberjunky** [comment]
Thank you for reporting, can you try version 0.2.25?

**Comment by micium** [comment]
> Thank you for reporting, can you try version 0.2.25?

same problem

**Comment by cyberjunky** [comment]
> > Thank you for reporting, can you try version 0.2.25?
> 
> same problem

The log you posted and deleted is actually another issue, what do you see exactly, do you get the hrvSummary TypeError or not? I

**Comment by nckslater** [comment]
0.2.25 fixed it for me on 2024.12.4

**Comment by iamspido** [comment]
Getting the same error with 0.2.25

```
hass  | 2024-12-20 10:11:38.516 ERROR (MainThread) [custom_components.garmin_connect] Unexpected error fetching garmin_connect data
hass  | Traceback (most recent call last):
hass  |   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh
hass  |     self.data = await self._async_update_data()
hass  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
hass  |   File "/config/custom_components/garmin_connect/__init__.py", line 194, in _async_update_data
hass  |     if "hrvSummary" in hrv_data:
hass  |        ^^^^^^^^^^^^^^^^^^^^^^^^
hass  | TypeError: argument of type 'NoneType' is not iterable
```

HA: 2024.11.3

**Comment by micium** [comment]
> > > Thank you for reporting, can you try version 0.2.25?
> > 
> > 
> > same problem
> 
> The log you posted and deleted is actually another issue, what do you see exactly, do you get the hrvSummary TypeError or not? I

you are right, my IP was banned for too many attempts  but .. 

I changed my IP :-) and retry in removing and reinstall the Garmin integration and I got the same problem:

Questo errore ha avuto origine da un'integrazione personalizzata.

Registratore: custom_components.garmin_connect
Fonte: helpers/update_coordinator.py:379
Integrazione: Garmin Connect (documentazione, problemi)
Prima occorrenza: 11:11:32 (3 occorrenze)
Ultimo accesso: 11:11:58

Unexpected error fetching garmin_connect data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/garmin_connect/__init__.py", line 194, in _async_update_data
    if "hrvSummary" in hrv_data:
       ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

**Comment by cyberjunky** [comment]
@micium this a minor difference to the issue fixed, I will fix it in a bit.

**Comment by micium** [comment]
> @micium this a minor difference to the issue fixed, I will fix it in a bit.

I replaced the hrv code with no problem:

try:
    if hrv_data is not None and "hrvSummary" in hrv_data:
        hrvStatus = hrv_data["hrvSummary"]
        _LOGGER.debug(f"HRV status: {hrvStatus}")
    else:
        _LOGGER.debug("HRV data is not available or null")
except KeyError:
    _LOGGER.debug("HRV data is not available due to missing key")

**Comment by cyberjunky** [comment]
Yeah update is coming in 0.2.26
```
if hrv_data and "hrvSummary" in hrv_data:
```

**Comment by cyberjunky** [comment]
Version 0.2.26 is available with the fix

**Comment by iamspido** [comment]
Can confirm the fix and close the issue.

**Comment by micium** [comment]
The version of 0.2.26 is ok, just out of curiosity, I would like to point out that my Fenix ​​5 does not measure HRV status, why do the other sensors correctly translate the status into "unknown" while this remains in UNKNOWN?
![unknown](https://github.com/user-attachments/assets/2fd0571a-eb68-4bb1-8ad6-5c90715cb389)
