### ISSUE TITLE
Fails on latest update 0.1.6 ha 2021.12.07

### ISSUE THREAD

**Issue by bschatzow** [cyberjunky/home-assistant-garmin_connect#23]
:39 PM – (WARNING) Template - message first occurred at 3:21:39 PM and shows up 3 times
Setup failed for garmin_connect: Unable to import component: No module named 'garminconnect_ha
Setup.py. .01.4 and .0.1.5 work.

**Comment by cyberjunky** [comment]
@bschatzow Hi thank you for reporting, can you try version 0.1.7?

**Comment by BebeMischa** [comment]
0.1.7 fixed for me... ;-)

**Comment by bschatzow** [comment]
> @bschatzow Hi thank you for reporting, can you try version 0.1.7?

Fixed for me as well.
