### ISSUE TITLE
Intensity minutes

### ISSUE THREAD

**Issue by KHV8** [cyberjunky/home-assistant-garmin_connect#27]
Hi,

The "Intensity Goal" entity is there. The 
  Moderate Intensity
  Vigorous Intensity
is mentioned in the documentation., however I do not have them. I know they should be disabled like the Intensity Goal.

I have installed yesterday using HACS on a RPi4. running versioin 0.1.8

Anything I can do to help/check

**Comment by cyberjunky** [comment]
Can you update to latest version, and then open the garmin intergration, look at all device and enable sensor.vigorous_intensity  and sensor.moderate_intensity en enabled them, then wait a few minutes, they should show up

**Comment by cyberjunky** [comment]
Closing, stale ticket.
