### ISSUE TITLE
All sensors remain "unknown" even after 12+ hours of running

### ISSUE THREAD

**Issue by tr1plus** [cyberjunky/home-assistant-garmin_connect#28]
Hi

This integration was working for me for a while and suddenly it no longer does. All sensors show as "unknown".

Running this integration on ver 1.8, with HA 2021.12.10

I get the "forbidden url" error (#26) twice in my logs, but both have happened over 11 hours ago now, and I still get no sensor data.
I have tried restarting HA a few times to get this to work and leave it sitting for 12+ hours, no luck so far.
I had issues getting this to work in the beginning, but indeed running HA for a few hours would fix it in the past.

I have updated some HA versions (started happening in 2021.12.07 I think) during it being broken initially and now, but all had the same issue.
I also updated to the latest integration version 1.8 yesterday, as I wasn't running latest version. However it's been running now for 15 hours and still no data appeared.

Not sure what else I can check.

Thanks!

**Comment by cyberjunky** [comment]
Can you login with your webbrowser to Garmin Online to see if you get extra questions/validation?

**Comment by tr1plus** [comment]
I'm able to connect to https://connect.garmin.com/
I use it practically daily to plot routes for cycling :) Or might that be the issue that I manually login constantly?

**Comment by tr1plus** [comment]
Wait - it started working suddenly...

I resynched my watch to my phone and it popped things up.

Maybe it was an issue on garmin side where it was showing "unknown" instead of "0"

**Comment by tr1plus** [comment]
going to close this - but will keep an eye on things.
It seems that if the device is not properly synced, it doesn't show anything on garmin connect, hence also not in the API.

I think the main confusion comes from the sensor status showing "unkown". Where I usually consider this as the integration not working, here it was a sign of no data being available.
