### ISSUE TITLE
Error login

### ISSUE THREAD

**Issue by ombarres** [cyberjunky/home-assistant-garmin_connect#29]
Hi,
I am trying to connect, but i have problems with the credentials. There are a solution? Or the problem its garmin?

**Comment by hermannx5** [comment]
Hi, I seem to have the same problem...cannot login...

**Comment by christensenjames** [comment]
Same here

**Comment by jeroen94704** [comment]
Same with me.

**Comment by KeithyMcC86** [comment]
Similiar issue. Changed password to remove special characters and still unable to log in.

**Comment by pcking99** [comment]
Couldn't log in had to change my password. After that i could but now im getting another error "Forbidden url".

**Comment by fudu** [comment]
Same for me, login error, no special characters

**Comment by MobThink** [comment]
same for me. login error. Credentials confirmed working on the Garmin portal.

**Comment by cyberjunky** [comment]
Closing old ticket. normally installing, configure, and it will retry to connect and succeed at some point

**Comment by andylockran** [comment]
Can we increase the error logging here at least to work out why I can't login.  The only error message I get is not detailed enough to work out what I've done wrong, but doesn't appear to be the rate limit .etc

Happy to submit a PR to improve the logging safely?
