### ISSUE TITLE
sensor.next_alarm_time not shown when irregular alarm schedule

### ISSUE THREAD

**Issue by jan-gerard** [cyberjunky/home-assistant-garmin_connect#30]
The sensor.next_alarm_time entity nicely shows the next alarm time when I have a single alarm set, but when I have a schedule (e.g. 'weekdays') there is no next alarm time shown. It looks like the integration has some trouble handling that. Or do I do something wrong on my watch or with synchronizing? 
I would like to couple responses of HA to my wake-up time.

**Comment by Broekman** [comment]
For me this works properly with v0.2.3 (set an alarm for all weekdays), some things with timestamps was fixed in that version.
