### ISSUE TITLE
`sensor.next_alarm_time` is providing a string for it's state

### ISSUE THREAD

**Issue by IceBotYT** [cyberjunky/home-assistant-garmin_connect#31]
On load of the integration, Home Assistant logs the following error:
`WARNING (MainThread) [homeassistant.components.sensor] sensor.next_alarm_time is providing a string for its state, while the device class is 'timestamp', this is not valid and will be unsupported from Home Assistant 2022.2. Please report it to the custom component author.`

Please fix this as fast as possible to make sure the integration continues working.

**Comment by IceBotYT** [comment]
Good news: [the owner is now aware of the issue](https://twitter.com/cyberjunky/status/1517219820231708672?s=20&t=sngW1bSgWk_Vk4A-jkU1wg)

**Comment by cyberjunky** [comment]
I just release version 0.1.9, but i could not reproduce/nor test, since I don't get this warning and everything worked fine all the time. So no idea what the stress is about...

**Comment by cyberjunky** [comment]
Had to delete it, hold on

**Comment by cyberjunky** [comment]
Please try 0.1.9, will look into other nextalarm related issues/requests later, not yet sure how to implement those at the moment.

**Comment by IceBotYT** [comment]
Thank you! This fix worked perfectly. This deprecation took effect somewhere in 2022.2, by the way.
