### ISSUE TITLE
sensor.next_alarm_time shows "unavailable" while there is an alarm set in Garmin Connect

### ISSUE THREAD

**Issue by madjo80** [cyberjunky/home-assistant-garmin_connect#32]
Since the March release of HA, I have had an issue with next_alarm_time. Not sure if that's HA related or Garmin related.
But all I know is that since the March release, the next_alarm_time says that it's "unavailable". But I have several alarms set in Garmin Connect.

All other Garmin data do get updated though, As far as I can see, it's only the Next Alarm Time that remains unavailable.
So it could very well be a change in the API on Garmin side, which happened to coincide with when I updated my HA-setup.

**Comment by Broekman** [comment]
For me this works properly with v0.2.3, some things with timestamps was fixed in there.

**Comment by dgeisse** [comment]
Not sure if that is related, but for me this error came up after the recent updates. Now the log is full with the following error occuring every 5 minutes: 
`ValueError: Sensor sensor.next_alarm_time has a state class and thus indicating it has a numeric value; however, it has the non-numeric device class: timestamp`

**Comment by mekaneck** [comment]
I just installed this integration for the sole purpose of feeding my watch's next alarm time into HA. After installation, all sensors worked except next alarm, which showed "unknown" even though I had an alarm set. I added another alarm for a different time, and the new one showed up. I removed the new one and the sensor reverted to unknown. I turned off my old alarm, sync'd with the GC app, and waited 5 minutes, then turned the alarm back on and sync'd and 5 minutes later still nothing changed. I then just deleted that old alarm and created an identical one in its place. Now it shows up in HA. 

My summary is that it seems like there is something with old or existing alarms that prevents them from being exposed to the integration. Deleting them and creating new ones seems to be the resolution.

**Comment by motionist** [comment]
I've been using the next alarm for an automation for some months. On Thursday after upgrading home Assistant to 2023.05.3 the next alarm entity is missing

**Comment by cyberjunky** [comment]
I will have a look, thanks for report

**Comment by cyberjunky** [comment]
Fixed in version 0.2.16
