### ISSUE TITLE
Installed through HACS but not showing up in integrations

### ISSUE THREAD

**Issue by Flatericuk** [cyberjunky/home-assistant-garmin_connect#33]
Hi, 

When I go to set up new integration after installing through HACS it does not appear in my list. Cleared cache, rebooted numerous times and reinstalled but hitting the same issue.

Any advice appreciated

**Comment by KeithyMcC86** [comment]
I'm seeing the same issue on HA Core 2022.3.8 either via installing through HACS or manual installation.
