### ISSUE TITLE
Failed to connect while logging in for first time

### ISSUE THREAD

**Issue by neebski** [cyberjunky/home-assistant-garmin_connect#40]
Just downloaded and installed via HACS.

Rebooted as reqd.

When logging in for the first time I receive an error stating failed to connect. Nothing in the logs. I do not have 2FA enabled on this account. 

Any suggestions?

**Comment by mzlarsson** [comment]
Just did the same thing (downloaded with HACS and tried to login) and got the same thing: "Failed to connect".

**Comment by mzlarsson** [comment]
Update: I did some local debugging towards https://pypi.org/project/garminconnect/ , which this repo depends upon. I managed to login a few times but most of the times it gives me an `GarminConnectConnectionError` with the cause `Forbidden url: https://sso.garmin.com/sso/signin`. But it's weird that it works sometimes and other times not at all. Will continue to look into it.

**Comment by mzlarsson** [comment]
I updated config_flow.py with code to retry at maximum 10 times when trying to connect. So basically the same solution as you. It wasn't pretty but did the deal, and now it seems to be syncing alright. 
@cyberjunky I'm not really suggesting to add it publicly (because it's ugly) but it would be an effective way to get people through the configuration phase with less of a hazzle.

**Comment by kksligh** [comment]
> I updated config_flow.py with code to retry at maximum 10 times when trying to connect. So basically the same solution as you. It wasn't pretty but did the deal, and now it seems to be syncing alright.

Can you give a little detail on how you did this?

**Comment by donster22** [comment]
I had this "failed to connect" problem. it took about 10 attempts and before logging in and now all seems well.

is there any way to expose the battery level of the Garmin device btw? I sometimes miss the reminders so wanted to automate something more obvious in HA.

**Comment by cyberjunky** [comment]
Battery level of devices is not available on Garmin Connect Website I think, at least not found in API
