### ISSUE TITLE
No values returned

### ISSUE THREAD

**Issue by PetrMa** [cyberjunky/home-assistant-garmin_connect#43]
Hi,

I installed the plugin without any issue. But after 24 hours I´ve got values only for 9 of 80 sensors. Other sensors are in the state Unknown.
Garmin Connect dashboard is synced and shows all correct data.
It is only my issue or general problem?
I want to know it before I enable debug logs etc.

Thanks, Regards,
Petr

**Comment by Broekman** [comment]
I had similar issues with the "Wellness start time" sensor enabled, where it stopped parsing several sensors.

See https://github.com/cyberjunky/home-assistant-garmin_connect/issues/46. 

Try disabling that sensor in Home Assistant.

Also, quote: "I want to know it before I enable debug logs etc". Next time please don't be lazy and just do it directly, it is one minute of work to enable debug logs and without it the developers (who do this for free), have to put a lot more effort into helping you out.

**Comment by cyberjunky** [comment]
Can you try version 0.2.3 it should still work with those sensors enabled.

**Comment by cyberjunky** [comment]
Think this is fixed, so closing.
