### ISSUE TITLE
[Question/help] Automatically synchronize smart watch to Garmin Connect

### ISSUE THREAD

**Issue by Broekman** [cyberjunky/home-assistant-garmin_connect#47]
Hi,

Apologies for asking this here, I know this isn't a problem with the integration, but it has often proven that my fellow automation colleagues have some nifty tricks for the little problems in our lives.

After going through every setting in the app/watch, searching for options online and even calling with a Garmin developer via their support desk, I have yet to find a resolution for getting my watch automatically synced to Garmin Connect (Garmin told me this wasn't possible, but I've heard that before).

Currently my watch (or rather the app) synchronizes to the cloud (Connect) in two ways:
1. Automatically after saving an activity on the watch (which for me only happens max. once a day after swimming).
2. When opening the Garmin Connect app on my phone, or of course manually syncing through the app or watch.

What I would like to see is that the watch/app automatically syncs in the background. Every 15-30 min. would be more than sufficient. At the moment when I don't open the app it just never syncs to Connect, which becomes especially annoying when it's not done before midnight as it resets making me lose the values of the day.

I know this is not an issue of this integration, it simply retrieves every five minutes what's on Connect, however I was wondering if any of you ever ran into this and perhaps have a neat little trick to work around it? At the moment it's a bit pointless for me to have my watch connected to Home Assistant as I'm not really able to automate anything or show data/progress without any values coming in on an "acceptable" interval.

**Phone:** Google Pixel 6a
- Android 13.
- Background access enabled (also properly sends notifications directly etc...).
- Battery saving fully disabled.
- Garmin Connect 4.61 (latest).
- Closing or leaving the application open makes no difference.

**Watch:** Garmin Vivoactive 4

Many thanks in advance!

**Comment by jbrepogmailcom** [comment]
Hello. Some vendors have aggressive application killing, could that be a reason? Check in battery settings if the Connect app is exclude from battery savings, and elsewhere in settings if killing the app is turned off. Of course allow all permissions. I would also try if the app synchronizes if you leave the phone on charging - aggressive app killing could be suspended during charging.
Other than that, I would try to completely uninstall/reinstall Connect.
My daughters have same watch and it synces well.
Could be also problem of the watch, if it can trigger sync after activity and not other times. Maybe some power settings?

**Comment by Broekman** [comment]
Thank you for taking the time to respond!

- Battery saving disabled for the app
- Connect has all permissions and runs in the background (i.e. notifications etc... come through instantaneous).
- Allowed to use background network data.
- Same behavior when charging
- Tried reinstalling, no change
- Went through all settings in the watch again, and anything related to auto upload etc... is enabled.

Could be something in Android 13 where it's more strict. Google Pixel phone's are typically on the latest Android release, so it might be that your daughters are still on 12 or lower? Anyhow, I will continue my search, thanks!

**Comment by teranex** [comment]
@Broekman did you ever find a solution? I'm seeing the same behaviour with my Venu 2 plus in combination with my OnePlus 7Pro which is still on Android 12.
I have now just setup a Tasker task to launch the Connect app at 23:55 so (I hope) it at least syncs at the end of the day, but that feels very clumsy.

**Comment by Broekman** [comment]
Hi @teranex, never found a solution I'm afraid. On Android 14 now, same behavior. I do something similar and have Home Assistant send a launch app command at 23:50 to open the Garmin Connect app on my phone. I could do it more often during the day but don't need the granularity right now.

https://companion.home-assistant.io/docs/notifications/notification-commands#launch-app

**Comment by teranex** [comment]
@Broekman thx for your reply! I also learned I can launch applications through Home Assistant now :)
While searching a bit more yesterday I also came across https://github.com/tcgoetz/GarminDB. This seems like a cool project to get all your data (including history) from Connect, but completely separate from HA

**Comment by Broekman** [comment]
@teranex and @sebcou21 for me it is working properly now.

I don't know exactly when it started working, could be since I switched to a Venu 3 or since some Connect update, but for me it is now syncing properly without any additional action. Still the same phone (Pixel 6a), Android 15 now.
