### ISSUE TITLE
Long term stats' not available for garmin connect sensors sensors

### ISSUE THREAD

**Issue by mrsnyds** [cyberjunky/home-assistant-garmin_connect#52]
Hi,

In trying to configure a [Statistics Graph Card](https://www.home-assistant.io/dashboards/statistics-graph) for the Garmin Connect sleep sensors, I discovered that it (along with the other Garmin Connect sensors) are not configured correctly for statistics tracking.  The documentation for the [Statistics Graph Card](https://www.home-assistant.io/dashboards/statistics-graph) includes a statement that points to what needs to be done ...

> "If your sensor doesn’t work with statistics, check [this](https://www.home-assistant.io/more-info/statistics/)."

The document at that link points to the solution in this developer document:

> 

> [Long-term Statistics](https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics)

**Comment by cyberjunky** [comment]
@mrsnyds you can use the sensor for long time graphs now, let me know if this is still an issue.

**Comment by mrsnyds** [comment]
Thanks for looking into this.  I can now see the sensors in the pick list if I scroll through it (see first attached), but just typing the beginning of the sensor entity name, like for the entity in the first picture, "sensor.ac..." should scroll right to the item as well, but it does not (see second attached).

Initially I thought the fix did not work, since I just tried to type the entity name and did not find it, but then I tried just looking through the list and I could find it.   So I can use the card now, but I'm wondering if you could find a fix for this second UI thing?

![Screenshot_20230107-100041_Home Assistant](https://user-images.githubusercontent.com/41122989/211157445-7bf2c713-f527-4537-a894-e9e19d4183ec.jpg)
![Screenshot_20230107-100624_Home Assistant](https://user-images.githubusercontent.com/41122989/211157485-d1aa92d5-08c3-4ffc-975a-d6155d21a842.jpg)

**Comment by cyberjunky** [comment]
This is a Home Assistant thing, you search for sensor friendly name, not entities So type 'Ac..' for Active...
