### ISSUE TITLE
Incorrect device_class

### ISSUE THREAD

**Issue by rcblackwell** [cyberjunky/home-assistant-garmin_connect#55]
Today I updated home_assistant_garmin_connect to version 2.5 from 2.3. Two entities now show up in a "Low Battery" script that I'm running in HA. The devices are sensor.body_fat and sensor.bone_mass. Both devices are listed listed with a device class of **device_class: battery**. I doubt this is the correct classification as the unit_of_measurement for these devices is KG. Please look into why these devices are listed as having a device_class of battery as there are interfering with proper operation of my Low Battery script.

![Garmin Entity Class](https://user-images.githubusercontent.com/70527431/210663041-2a881974-599a-43cd-a747-18d1df24f878.png)

**EDIT:** I also see sensor.body_water listed with a **device_class: battery**.

**Comment by Tazmanian79** [comment]
Same here.

In the logs is this entrie:

Entity sensor.bone_mass (<class 'custom_components.garmin_connect.sensor.GarminConnectSensor'>) is using native unit of measurement 'kg' which is not a valid unit for the device class ('battery') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.

**Comment by cyberjunky** [comment]
Arg yes, thanks.! Thought it was % which of course it isn't for bone mass, and possible a few othrs, didn't know HA checks this, nice, will fix today together with some other things

**Comment by Tazmanian79** [comment]
I think in my case it's for all these entities:
        - sensor.body_fat_2
        - sensor.body_water_2
        - sensor.bone_mass_2
        - sensor.bone_mass
        - sensor.body_fat
        - sensor.body_water

**Comment by cyberjunky** [comment]
I fixed them in version 0.2.6 (I hope ;-) )

**Comment by Tazmanian79** [comment]
I don't have this error anymore in my log after this update.
But the following sensors have still "device_class: battery"

sensor.body_fat
sensor.body_water

**Comment by rcblackwell** [comment]
I concur. Those two sensors are still listed with a device class of 
battery.


-------------------------
Robert Blackwell
Stratford, ON


------ Original Message ------
From "Tazmanian79" ***@***.***>
To "cyberjunky/home-assistant-garmin_connect" 
***@***.***>
Cc "Robert" ***@***.***>; "Author" 
***@***.***>
Date 2023-01-06 8:16:16 AM
Subject Re: [cyberjunky/home-assistant-garmin_connect] Incorrect 
device_class (Issue #55)

**Comment by cyberjunky** [comment]
This is correct, there are more of them to be honest, there is no other device class defined in Home Assistant core code supporting % as unit, so was kinda forced to use it, but I will have a look if we can do this more elegant.

**Comment by Tazmanian79** [comment]
Maybe = moisture: Percentage of water in a substance

**Comment by rcblackwell** [comment]
Good point.

________________________
Robert Blackwell
Phone: (C) 289 314-0920
              (H) 519 272-0198

**Comment by homonto** [comment]
I am on 0.2.6 and still few sensors are "battery" class:
Activity Stress Percentage (2%)
Uncat. Stress Percentage (2%)
Body Lowest (6%)
Medium Stress Percentage (7%)
Body Drained (8%)
Low Stress Percentage (12%)

**Comment by dgeisse** [comment]
Related to that, I am seeing an error with the state class of sensor.next_alarm_time 

Referencing my comment in [this](https://github.com/cyberjunky/home-assistant-garmin_connect/issues/32#issuecomment-1374209739), sorry for posting it twice

**Comment by cyberjunky** [comment]
Changed 

> Related to that, I am seeing an error with the state class of sensor.next_alarm_time
> 
> Referencing my comment in [this](https://github.com/cyberjunky/home-assistant-garmin_connect/issues/32#issuecomment-1374209739) issue, sorry for posting it twice

Should be fixed in 0.2.7

**Comment by cyberjunky** [comment]
Should be fixed in 0.2.8, can you test and report back please...

**Comment by rcblackwell** [comment]
@cyberjunky , The entities that were appearing in my battery sensor script no longer do. Version 2.8 looks promising. Thank you for your work on this integration. much appreciated.

**Comment by cyberjunky** [comment]
> thank you @cyberjunky for info. I don't see anymore "body percent" in my battery devices anymore but there is 1 thing: why do we have to restart HA after each Garmin Connect update?

It's the way HA works with HACS and custom integrations I guess.
I will put on my todo list if I can improve this.

**Comment by cyberjunky** [comment]
Stale ticket, closing for now... item is still on todo list.
