### ISSUE TITLE
All sensors show Unknown even though they have data.

### ISSUE THREAD

**Issue by mkaltner** [cyberjunky/home-assistant-garmin_connect#57]
I've seen this for some time, can't say how long or which versions but I did just updated to 0.2.6 (hass 2023.1.1 docker compose image homeassistant/home-assistant:stable) and still see this.
As the screenshot shows, there's data but all the sensors show as Unknown in the frontend.  I have debug logging enabled and don't see errors that seem related, just:

ValueError: Sensor sensor.next_alarm_time has a state class and thus indicating it has a numeric value; however, it has the non-numeric device class: timestamp

I removed the integration and re-added/connected to make sure everything is fresh.

Any thoughts on how get some data showing up?  It worked once upon a time...

![2023-01-06 22_07_46-Settings – Home Assistant and 4 more pages - Personal - Microsoft​ Edge](https://user-images.githubusercontent.com/4999672/211133955-766169eb-9687-4e16-8f56-52d75b1845d0.png)

**Comment by mkaltner** [comment]
I saw the closed issue and it didn't mention any data but like they did, I synced the app again and data showed up.  Same issue I suppose, just thought it strange that there is data history but still shows Unknown.  One thing to note is that it is now the next day (just after midnight) and the data is showing up now.  Perhaps it happens if there isn't a full day of history.

**Comment by cyberjunky** [comment]
Around midnight sensor data is unavailable, don't know the cause, was like this since the beginning, looking into a way to keep old values during this time.
