### ISSUE TITLE
Versioning and multiple users

### ISSUE THREAD

**Issue by DrewXT** [cyberjunky/home-assistant-garmin_connect#6]
Hi Ron,

loving that you've moved this across to HACS - got a questions.  I have two accounts set up, one for me, and one for my wife.  I can successfully retrieve data for one account at a time, but not when both are configured.  Not sure if (or how to do it) there needs to be a check for the integration running multiple retrievals consecutively, and offset them by a minute if there are?

**Comment by cyberjunky** [comment]
Do you still have this issue? Sometimes after login failure it corrects itself.

**Comment by DrewXT** [comment]
> Do you still have this issue? Sometimes after login failure it corrects itself.

Sometimes it works straight after a restart, but sometimes it can take hours or days to sort itself out, or even not at all.

I'm wondering if you're making multiple calls for different accounts at the same time, based on the log entries indicating multiple logins from the same IP and then denied by Garmin ...

**Comment by cyberjunky** [comment]
Please try with latest version and open ticket if you still have issues.
