### ISSUE TITLE
sensor.next_alarm_time (wrongly?) assumes UTC

### ISSUE THREAD

**Issue by arniebarni** [cyberjunky/home-assistant-garmin_connect#60]
After my last update - I believe from 0.2.2 to 0.2.6 (and now 0.2.7) - my `sensor.next_alarm_time` is off by exactly one hour.
My Garmin device is of course in local time, which is GMT+1. My home assistant runs in a docker container on a Raspberry Pi 4, with host and container also configured  for GMT+1. From the logs I can see, that the alarm time if pulled in localtime:
```
2023-01-08 15:28:26.143 DEBUG (MainThread) [custom_components.garmin_connect] [{'alarmMode': 'ON', 'alarmTime': 360, 'alarmDays': ['M', 'Tu', 'W', 'Th', 'F', 'Sa', 'Su'], 'alarmSound': ...
```
So that's 6 a.m. local time. However, this integration now assumes a utc timestamp. Of course this can be fixed on my template side of things, however this seems to be the wrong way to me.

What's your opinion on using the system timezone instead of utc? After all I believe most users would have the same time zone on the Garmin device and their home assistant host.

Possible changes in `sensor.py` using the `datetime` package as such:
```python
now = datetime.datetime.now()
local_now = now.astimezone()
local_tz = local_now.tzinfo
local_tzname = local_tz.tzname(local_now)
timezone = pytz.timezone(local_tzname)
```
without additional imports or using `tzlocal`
```python
timezone = pytz.timezone(tzlocal.get_localzone_name())
```
Let me know what you think, I'll happily prepare a pull request if needed.

Arne

**Comment by cyberjunky** [comment]
@arniebarni yes noticed this too, and was on my todo list, please open a PR if you want! Thanks!

**Comment by arniebarni** [comment]
I guess another way would be using the preferred time zone from the garmin account which could be exposed in your python-garminconnect. Not sure what's better.
