### ISSUE TITLE
Syncing

### ISSUE THREAD

**Issue by davidjac** [cyberjunky/home-assistant-garmin_connect#70]
How does syncing work? I always assume data is wrong but having looked a bit further I see data is four hours ago as last sync. Is there a way to force it/set it for more regular?

**Comment by cyberjunky** [comment]
It displays the data as it is available on the Garmin Connect website, so it depends on how often you sync your watch/devices

**Comment by davidjac** [comment]
> It displays the data as it is available on the Garmin Connect website, so it depends on how often you sync your watch/devices

THanks.
