### ISSUE TITLE
not connecting to Garmin

### ISSUE THREAD

**Issue by homonto** [cyberjunky/home-assistant-garmin_connect#8]
guys, I tried million times - it does not allow to login even to Garmin
what am I missing?
installed via HACS, restarted HA, adding integration, entering credentials and ... "login failed"

thx for help

**Comment by bradfree63** [comment]
Same issue here and definitely using correct credentials.

**Comment by homonto** [comment]
mine "started" working suddenly - IDK why and how

**Comment by bradfree63** [comment]
Tried again after receiving your post and it connected on second attempt and restart.

**Comment by moorboss** [comment]
This is what I had a few days again, the login now works, but it never got started, it returns the message: Retrying setup: 'NoneType' object is not iterable

**Comment by BebeMischa** [comment]
Working correctly here, no any issues for about three months now.

**Comment by lukim198301** [comment]
it's not connecting to garmin account. Could not to connect error

**Comment by cyberjunky** [comment]
The initial connect after installing or restart of home assisant is somewhat too aggresive,so it fails a lot, after a few retries is works, I will look into this soon.

**Comment by ArnyminerZ** [comment]
For me it wasn't working for the first time, but rebooted the server and worked fine.

**Comment by cyberjunky** [comment]
Closing for now, sometimes initial connect is failed, but give it some time
