### ISSUE TITLE
Retrying setup: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by moorboss** [cyberjunky/home-assistant-garmin_connect#9]
I get the constantly the message: Retrying setup: 'NoneType' object is not iterable and the Garmin Coonnect integration is not working. Tried many times, reinstalling restarting etc. Now ginving up, until some suggestions can be given find the solution. 

Every suggestion is appreciated.

**Comment by moorboss** [comment]
AFter a while, it turns out to be that the plugin tries to login several times and gets kicked out by Garmin connect for a while. So even I cannot connect anymore with my mobile phone or webbrowser to Garmin connect.

**Comment by moorboss** [comment]
Tobe sure that there is nothing wrong with my HA installation, I have been trying to connect with the garmin account of my wife. That works as a charm. SO the culprit must be my Garmin account. 

Thi is the error message:
Unexpected error fetching garmin_connect data: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/garmin_connect/__init__.py", line 99, in _async_update_data
    alarms = await self.hass.async_add_executor_job(self._api.get_device_alarms)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/garminconnect_ha/__init__.py", line 206, in get_device_alarms
    alarms += device_settings["alarms"]
TypeError: 'NoneType' object is not iterable

Any thoughts?

**Comment by cyberjunky** [comment]
Just create an alarm, and disable it was the fix I think.

**Comment by moorboss** [comment]
It i snot about fixing it with alarms. The problem is about registred gear in Garmin Connect which is (temporarily) not in use. When removing those items, it worked like a flaw. (maybe good to add to the known issues!

**Comment by PointingP** [comment]
Removing gear in Garmin Connect did not fix the issue, unless it's also about Golf clubs (I don't even play golf), which can't be removed - when you remove the last club it repopulates the Golf gear list with a bunch of clubs?!
