### ISSUE TITLE
Not showing any data

### ISSUE THREAD

**Issue by jbrepogmailcom** [cyberjunky/home-assistant-garmin_connect#99]
Hello, for some unknown reason the Garmin integration does not receive any data. It worked fine before, but is not working now. I suspect HA upgrade. Can you confirm it works with Home Assistant 2023.8.4?

Thank you very much, Jan

**Comment by craigrouse** [comment]
It works fine for me. Do you see data in the Garmin app?

**Comment by jbrepogmailcom** [comment]
Working now. Reloaded the integration, I do not know if that solved it.
